var newConnection = [
	{
		"image1" : "images/1a.JPG",
		"image2" : "images/1b.JPG",
		"image3" : "images/1c.jpg",
		"image4" : "images/1d.JPG",
		"answer" : "Tom Hennessy House",
	},
	{
		"image1" : "images/2a.JPG",
		"image2" : "images/2b.JPG",
		"image3" : "images/2c.JPG",
		"image4" : "images/2d.jpg",
		"answer" : "Yankees Merchandise",
	},
	{
		"image1" : "images/3a.jpg",
		"image2" : "images/3b.jpg",
		"image3" : "images/3c.jpg",
		"image4" : "images/3d.jpg",
		"answer" : "Sammy's Graduation Party",
	},
	{
		"image1" : "images/4a.PNG",
		"image2" : "images/4b.PNG",
		"image3" : "images/4c.PNG",
		"image4" : "images/4d.PNG",
		"answer" : "Short's",
	},
	{
		"image1" : "images/5a.PNG",
		"image2" : "images/5b.PNG",
		"image3" : "images/5c.PNG",
		"image4" : "images/5d.PNG",
		"answer" : "Lunch with Johnny and Malancha",
	},
	{
		"image1" : "images/6a.JPG",
		"image2" : "images/6b.jpg",
		"image3" : "images/6c.JPG",
		"image4" : "images/6d.JPG",
		"answer" : "Bills Merchandise",
	},
	{
		"image1" : "images/7a.jpg",
		"image2" : "images/7b.JPG",
		"image3" : "images/7c.JPG",
		"image4" : "images/7d.jpg",
		"answer" : "Sunglasses",
	},
	{
		"image1" : "images/8a.PNG",
		"image2" : "images/8b.PNG",
		"image3" : "images/8c.PNG",
		"image4" : "images/8d.jpg",
		"answer" : "Texas Hot",
	},
	{
		"image1" : "images/9a.PNG",
		"image2" : "images/9b.PNG",
		"image3" : "images/9c.jpg",
		"image4" : "images/9d.JPG",
		"answer" : "New York City",
	},
	{
		"image1" : "images/10a.jpg",
		"image2" : "images/10b.jpg",
		"image3" : "images/10c.jpg",
		"image4" : "images/10d.jpg",
		"answer" : "First Day of School",
	},
	{
		"image1" : "images/11a.PNG",
		"image2" : "images/11b.PNG",
		"image3" : "images/11c.jpg",
		"image4" : "images/11d.PNG",
		"answer" : "In Cars",
	},
	{
		"image1" : "images/12a.jpg",
		"image2" : "images/12b.jpg",
		"image3" : "images/12c.jpg",
		"image4" : "images/12d.jpg",
		"answer" : "Snow",
	},
	{
		"image1" : "images/13a.jpg",
		"image2" : "images/13b.PNG",
		"image3" : "images/13c.PNG",
		"image4" : "images/13d.PNG",
		"answer" : "Costumes",
	},
	{
		"image1" : "images/14a.jpg",
		"image2" : "images/14b.JPG",
		"image3" : "images/14c.JPG",
		"image4" : "images/14d.JPG",
		"answer" : "Caught a Fish",
	},
	{
		"image1" : "images/15a.JPG",
		"image2" : "images/15b.jpg",
		"image3" : "images/15c.jpg",
		"image4" : "images/15d.jpg",
		"answer" : "Graduation",
	},
	{
		"image1" : "images/16a.JPG",
		"image2" : "images/16b.JPG",
		"image3" : "images/16c.jpg",
		"image4" : "images/16d.jpg",
		"answer" : "Doing a Puzzle",
	},
	{
		"image1" : "images/17a.JPG",
		"image2" : "images/17b.jpg",
		"image3" : "images/17c.jpg",
		"image4" : "images/17d.jpg",
		"answer" : "Weddings",
	},
	{
		"image1" : "images/18a.JPG",
		"image2" : "images/18b.JPG",
		"image3" : "images/18c.JPG",
		"image4" : "images/18d.JPG",
		"answer" : "Brockport Merchandise",
	},
	{
		"image1" : "images/19a.JPG",
		"image2" : "images/19b.JPG",
		"image3" : "images/19c.jpg",
		"image4" : "images/19d.jpg",
		"answer" : "Rock City",
	},

];