var newSuperlatives = [
	{
		"superlatives" : "Most Likely to Succeed",
		"1name" : "Johnny",
		"1points" : "12",
		"2name" : "Malancha",
		"2points" : "3",
		"3name" : "Grandpa",
		"3points" : "2",
		"4name" : "Jessica",
		"4points" : "2",
		"5name" : "Sarah",
		"5points" : "2",
		"6name" : "Tom",
		"6points" : "1",
		"7name" : "Mart or Kelsey",
		"7points" : "1",
		"8name" : "Jim or Shannon",
		"8points" : "1",
	},
	{
		"superlatives" : "Class Clown",
		"1name" : "LJ",
		"1points" : "8",
		"2name" : "Mart",
		"2points" : "4",
		"3name" : "Jim",
		"3points" : "3",
		"4name" : "Greg",
		"4points" : "3",
		"5name" : "Tom",
		"5points" : "2",
		"6name" : "Grandpa",
		"6points" : "1",
		"7name" : "John",
		"7points" : "1",
		"8name" : "Josh or Sammy",
		"8points" : "1",
	},
	{
		"superlatives" : "Most likely to win lottery and lose the ticket",
		"1name" : "Chris",
		"1points" : "4",
		"2name" : "Grandma",
		"2points" : "4",
		"3name" : "John",
		"3points" : "3",
		"4name" : "Greg",
		"4points" : "3",
		"5name" : "Jessica",
		"5points" : "2",
		"6name" : "Josh",
		"6points" : "2",
		"7name" : "Joe",
		"7points" : "2",
		"8name" : "Jim or Patti",
		"8points" : "1",
	},
	{
		"superlatives" : "Most shy",
		"1name" : "Shea",
		"1points" : "12",
		"2name" : "Katie",
		"2points" : "6",
		"3name" : "Malancha",
		"3points" : "2",
		"4name" : "Shannon",
		"4points" : "1",
		"5name" : "Patti",
		"5points" : "1",
		"6name" : "Kelsey",
		"6points" : "1",
		"7name" : "Johnny",
		"7points" : "1",
		"8name" : "Nicole",
		"8points" : "1",
	},
	{
		"superlatives" : "Best shoulder to cry on",
		"1name" : "Nicole",
		"1points" : "4",
		"2name" : "Jessica",
		"2points" : "3",
		"3name" : "Margaret",
		"3points" : "3",
		"4name" : "Grandpa",
		"4points" : "2",
		"5name" : "LJ",
		"5points" : "2",
		"6name" : "Grandpa",
		"6points" : "2",
		"7name" : "Mary, Alyssa or Joe",
		"7points" : "1",
		"8name" : "Greg, Chris or John",
		"8points" : "1",
	},
	{
		"superlatives" : "Most likely to save the rain forest",
		"1name" : "Mary",
		"1points" : "13",
		"2name" : "Sarah",
		"2points" : "2",
		"3name" : "Malancha",
		"3points" : "1",
		"4name" : "Tom or Kendra",
		"4points" : "1",
		"5name" : "Shannon",
		"5points" : "1",
		"6name" : "Jessica",
		"6points" : "1",
		"7name" : "Mart or Katie",
		"7points" : "1",
		"8name" : "Peter or Malancha",
		"8points" : "1",
	},
	{
		"superlatives" : "Most optimistic",
		"1name" : "Joe",
		"1points" : "5",
		"2name" : "Alyssa",
		"2points" : "4",
		"3name" : "Mary",
		"3points" : "3",
		"4name" : "Grandma",
		"4points" : "3",
		"5name" : "John",
		"5points" : "2",
		"6name" : "LJ",
		"6points" : "2",
		"7name" : "Margaret",
		"7points" : "2",
		"8name" : "John",
		"8points" : "2",
	},
	{
		"superlatives" : "Most likely to ask about you/ your secrets",
		"1name" : "Margaret",
		"1points" : "12",
		"2name" : "Patti",
		"2points" : "2",
		"3name" : "Jessica",
		"3points" : "2",
		"4name" : "Sammy",
		"4points" : "2",
		"5name" : "Mart",
		"5points" : "1",
		"6name" : "Alyssa",
		"6points" : "1",
		"7name" : "Mary",
		"7points" : "1",
		"8name" : "Kendra",
		"8points" : "1",
	},
	{
		"superlatives" : "Best story teller",
		"1name" : "Grandpa",
		"1points" : "11",
		"2name" : "Kendra",
		"2points" : "8",
		"3name" : "Joe",
		"3points" : "3",
		"4name" : "John",
		"4points" : "2",
		"5name" : "Peter",
		"5points" : "1",
		"6name" : "Kelsey",
		"6points" : "1",
		"7name" : "0",
		"7points" : "0",
		"8name" : "0",
		"8points" : "0",
	},
	{
		"superlatives" : "Most creative",
		"1name" : "Sarah",
		"1points" : "17",
		"2name" : "Alyssa",
		"2points" : "3",
		"3name" : "Kendra",
		"3points" : "2",
		"4name" : "Mary",
		"4points" : "1",
		"5name" : "Mart",
		"5points" : "2",
		"6name" : "Greg",
		"6points" : "1",
		"7name" : "Shannon",
		"7points" : "1",
		"8name" : "0",
		"8points" : "0",
	},
	{
		"superlatives" : "Biggest Techie",
		"1name" : "Johnny",
		"1points" : "18",
		"2name" : "Tom",
		"2points" : "2",
		"3name" : "Sarah",
		"3points" : "1",
		"4name" : "LJ",
		"4points" : "1",
		"5name" : "Mart",
		"5points" : "1",
		"6name" : "Andrew",
		"6points" : "1",
		"7name" : "Kelsey",
		"7points" : "1",
		"8name" : "Grandma",
		"8points" : "1",
	},
	{
		"superlatives" : "Most talkative",
		"1name" : "Jim",
		"1points" : "5",
		"2name" : "Patti",
		"2points" : "4",
		"3name" : "Kendra",
		"3points" : "4",
		"4name" : "Mary",
		"4points" : "3",
		"5name" : "Joe",
		"5points" : "3",
		"6name" : "Malancha",
		"6points" : "2",
		"7name" : "Greg",
		"7points" : "2",
		"8name" : "Sammy or Jessica",
		"8points" : "1",
	},
	{
		"superlatives" : "Loudest",
		"1name" : "Jim",
		"1points" : "22",
		"2name" : "Patti",
		"2points" : "1",
		"3name" : "Sammy",
		"3points" : "1",
		"4name" : "Tom",
		"4points" : "1",
		"5name" : "Greg",
		"5points" : "1",
		"6name" : "0",
		"6points" : "0",
		"7name" : "0",
		"7points" : "0",
		"8name" : "0",
		"8points" : "0",
	},
	{
		"superlatives" : "Quietest",
		"1name" : "Shea",
		"1points" : "9",
		"2name" : "Shannon",
		"2points" : "3",
		"3name" : "Malancha",
		"3points" : "3",
		"4name" : "Johnny",
		"4points" : "3",
		"5name" : "Katie",
		"5points" : "2",
		"6name" : "Chris",
		"6points" : "2",
		"7name" : "Tom",
		"7points" : "1",
		"8name" : "Kelsey or Alyssa",
		"8points" : "1",
	},
	{
		"superlatives" : "Most likely to survive the Hunger Games",
		"1name" : "Greg",
		"1points" : "6",
		"2name" : "Sammy",
		"2points" : "3",
		"3name" : "Joe",
		"3points" : "3",
		"4name" : "Kelsey",
		"4points" : "2",
		"5name" : "Sarah",
		"5points" : "2",
		"6name" : "Jim",
		"6points" : "2",
		"7name" : "Malancha",
		"7points" : "2",
		"8name" : "LJ, Jessica or Katie",
		"8points" : "1",
	},
	{
		"superlatives" : "Best Dressed",
		"1name" : "Kelsey",
		"1points" : "6",
		"2name" : "Alyssa",
		"2points" : "5",
		"3name" : "Greg",
		"3points" : "3",
		"4name" : "Andrew",
		"4points" : "2",
		"5name" : "Shea",
		"5points" : "2",
		"6name" : "Jim or Patti",
		"6points" : "1",
		"7name" : "Johnny or Grandpa",
		"7points" : "1",
		"8name" : "LJ",
		"8points" : "1",
	},
	{
		"superlatives" : "Most athletic",
		"1name" : "Andrew",
		"1points" : "13",
		"2name" : "Jessica",
		"2points" : "10",
		"3name" : "Jim",
		"3points" : "2",
		"4name" : "Alyssa",
		"4points" : "1",
		"5name" : "0",
		"5points" : "0",
		"6name" : "0",
		"6points" : "0",
		"7name" : "0",
		"7points" : "0",
		"8name" : "0",
		"8points" : "0",
	},
	{
		"superlatives" : "Best Laugh",
		"1name" : "Chris",
		"1points" : "17",
		"2name" : "Katie",
		"2points" : "2",
		"3name" : "Johnny",
		"3points" : "2",
		"4name" : "Nicole",
		"4points" : "1",
		"5name" : "Greg",
		"5points" : "1",
		"6name" : "Joe",
		"6points" : "1",
		"7name" : "Grandma",
		"7points" : "1",
		"8name" : "Jessica",
		"8points" : "1",
	},
	{
		"superlatives" : "Most gullible",
		"1name" : "Malancha",
		"1points" : "6",
		"2name" : "Katie",
		"2points" : "5",
		"3name" : "Shannon",
		"3points" : "3",
		"4name" : "Chris",
		"4points" : "3",
		"5name" : "Nicole",
		"5points" : "3",
		"6name" : "Mary",
		"6points" : "2",
		"7name" : "LJ",
		"7points" : "1",
		"8name" : "Greg",
		"8points" : "1",
	},
	{
		"superlatives" : "Biggest Prankster",
		"1name" : "Grandpa",
		"1points" : "7",
		"2name" : "LJ",
		"2points" : "6",
		"3name" : "Andrew",
		"3points" : "5",
		"4name" : "Kendra",
		"4points" : "2",
		"5name" : "Grandma",
		"5points" : "1",
		"6name" : "Kelsey",
		"6points" : "1",
		"7name" : "Tom",
		"7points" : "1",
		"8name" : "Greg",
		"8points" : "1",
	},
	{
		"superlatives" : "Most likely to Host",
		"1name" : "Margaret",
		"1points" : "17",
		"2name" : "Grandma",
		"2points" : "3",
		"3name" : "Patti",
		"3points" : "2",
		"4name" : "Jim",
		"4points" : "1",
		"5name" : "Kendra",
		"5points" : "1",
		"6name" : "Johnny",
		"6points" : "1",
		"7name" : "0",
		"7points" : "0",
		"8name" : "0",
		"8points" : "0",
	},
	{
		"superlatives" : "Most likely to cheer you up",
		"1name" : "Katie",
		"1points" : "3",
		"2name" : "Grandma",
		"2points" : "3",
		"3name" : "Nicole",
		"3points" : "2",
		"4name" : "Mart",
		"4points" : "2",
		"5name" : "LJ",
		"5points" : "2",
		"6name" : "Grandpa",
		"6points" : "2",
		"7name" : "Andrew",
		"7points" : "2",
		"8name" : "Shea",
		"8points" : "2",
	},
	{
		"superlatives" : "Most likely to fight aliens and win",
		"1name" : "Johnny",
		"1points" : "5",
		"2name" : "Josh",
		"2points" : "4",
		"3name" : "Joe",
		"3points" : "3",
		"4name" : "Kelsey",
		"4points" : "3",
		"5name" : "Peter",
		"5points" : "3",
		"6name" : "Andrew",
		"6points" : "2",
		"7name" : "John",
		"7points" : "2",
		"8name" : "Tom or Mart",
		"8points" : "1",
	},
	{
		"superlatives" : "Most likely to swim in the lake",
		"1name" : "Sammy",
		"1points" : "9",
		"2name" : "LJ",
		"2points" : "6",
		"3name" : "Josh",
		"3points" : "4",
		"4name" : "Peter",
		"4points" : "2",
		"5name" : "Chris",
		"5points" : "2",
		"6name" : "Shea",
		"6points" : "1",
		"7name" : "Grandma",
		"7points" : "1",
		"8name" : "Shannon",
		"8points" : "1",
	},
	{
		"superlatives" : "Most likely to walk into the glass door",
		"1name" : "Jim",
		"1points" : "6",
		"2name" : "Nicole",
		"2points" : "3",
		"3name" : "Peter",
		"3points" : "3",
		"4name" : "Alyssa",
		"4points" : "2",
		"5name" : "Grandpa",
		"5points" : "2",
		"6name" : "Chris",
		"6points" : "2",
		"7name" : "Joe or Mary",
		"7points" : "1",
		"8name" : "LJ or Sammy",
		"8points" : "1",
	},
	{
		"superlatives" : "Most likely to wear all green",
		"1name" : "Grandma",
		"1points" : "9",
		"2name" : "Greg",
		"2points" : "3",
		"3name" : "Mart",
		"3points" : "2",
		"4name" : "Tom",
		"4points" : "2",
		"5name" : "Peter",
		"5points" : "1",
		"6name" : "Chris or Johnny",
		"6points" : "1",
		"7name" : "Katie",
		"7points" : "1",
		"8name" : "Grandpa",
		"8points" : "1",
	},
	{
		"superlatives" : "Most likely to be in their garden",
		"1name" : "Kendra",
		"1points" : "25",
		"2name" : "Greg",
		"2points" : "1",
		"3name" : "0",
		"3points" : "0",
		"4name" : "0",
		"4points" : "0",
		"5name" : "0",
		"5points" : "0",
		"6name" : "0",
		"6points" : "0",
		"7name" : "0",
		"7points" : "0",
		"8name" : "0",
		"8points" : "0",
	},
	{
		"superlatives" : "Captain of the boat",
		"1name" : "Grandpa",
		"1points" : "7",
		"2name" : "LJ",
		"2points" : "5",
		"3name" : "John",
		"3points" : "5",
		"4name" : "Tom",
		"4points" : "4",
		"5name" : "Joe",
		"5points" : "1",
		"6name" : "Shea or Sarah",
		"6points" : "1",
		"7name" : "Jim",
		"7points" : "1",
		"8name" : "Josh",
		"8points" : "1",
	},
	{
		"superlatives" : "Most likely to invent something on an infomercial",
		"1name" : "Jim",
		"1points" : "4",
		"2name" : "Sarah",
		"2points" : "4",
		"3name" : "Josh",
		"3points" : "3",
		"4name" : "Joe",
		"4points" : "2",
		"5name" : "Grandpa",
		"5points" : "2",
		"6name" : "Johnny",
		"6points" : "2",
		"7name" : "Greg",
		"7points" : "2",
		"8name" : "Andrew or Shannon",
		"8points" : "1",
	},
	{
		"superlatives" : "Most likely to get sent to the principal's office",
		"1name" : "Sammy",
		"1points" : "7",
		"2name" : "LJ",
		"2points" : "4",
		"3name" : "Peter",
		"3points" : "3",
		"4name" : "Greg",
		"4points" : "2",
		"5name" : "Jessica",
		"5points" : "2",
		"6name" : "Shea",
		"6points" : "1",
		"7name" : "Mary or Grandma",
		"7points" : "1",
		"8name" : "Malancha or John",
		"8points" : "1",
	},
	{
		"superlatives" : "Most likely to ride through the hospital zone",
		"1name" : "Shannon",
		"1points" : "9",
		"2name" : "Sammy",
		"2points" : "3",
		"3name" : "Chris",
		"3points" : "2",
		"4name" : "LJ",
		"4points" : "2",
		"5name" : "Nicole",
		"5points" : "2",
		"6name" : "Joe",
		"6points" : "1",
		"7name" : "Josh",
		"7points" : "1",
		"8name" : "Andrew",
		"8points" : "1",
	},
	{
		"superlatives" : "Most likely to ask about you/ your secrets",
		"1name" : "Greg",
		"1points" : "7",
		"2name" : "Josh",
		"2points" : "4",
		"3name" : "Peter",
		"3points" : "3",
		"4name" : "Sammy or Tom",
		"4points" : "2",
		"5name" : "Johnny",
		"5points" : "2",
		"6name" : "Andrew or Shannon",
		"6points" : "1",
		"7name" : "Malancha",
		"7points" : "1",
		"8name" : "Kelso",
		"8points" : "1",
	},
	{
		"superlatives" : "Most laid back",
		"1name" : "Johnny",
		"1points" : "9",
		"2name" : "Joe",
		"2points" : "5",
		"3name" : "Josh",
		"3points" : "2",
		"4name" : "Kelsey",
		"4points" : "2",
		"5name" : "John",
		"5points" : "2",
		"6name" : "LJ, Nicole or Katie",
		"6points" : "1",
		"7name" : "Greg",
		"7points" : "1",
		"8name" : "Tom or Shea",
		"8points" : "1",
	},
	{
		"superlatives" : "Most likely to get a speeding ticket",
		"1name" : "LJ",
		"1points" : "8",
		"2name" : "Joe",
		"2points" : "6",
		"3name" : "Mart",
		"3points" : "2",
		"4name" : "Sarah",
		"4points" : "2",
		"5name" : "Sammy",
		"5points" : "2",
		"6name" : "Grandma",
		"6points" : "1",
		"7name" : "Nicole or Jessica",
		"7points" : "1",
		"8name" : "0",
		"8points" : "0",
	},
	{
		"superlatives" : "Most likely to go to a festival",
		"1name" : "Josh",
		"1points" : "13",
		"2name" : "Mary",
		"2points" : "6",
		"3name" : "Greg",
		"3points" : "3",
		"4name" : "Joe",
		"4points" : "2",
		"5name" : "Shannon",
		"5points" : "1",
		"6name" : "0",
		"6points" : "0",
		"7name" : "0",
		"7points" : "0",
		"8name" : "0",
		"8points" : "0",
	},
	{
		"superlatives" : "Most likely to decorate your house",
		"1name" : "Alyssa",
		"1points" : "13",
		"2name" : "Kendra",
		"2points" : "5",
		"3name" : "Mart",
		"3points" : "2",
		"4name" : "John",
		"4points" : "2",
		"5name" : "Chris",
		"5points" : "1",
		"6name" : "Margaret",
		"6points" : "1",
		"7name" : "Grandma",
		"7points" : "1",
		"8name" : "0",
		"8points" : "0",
	},
	{
		"superlatives" : "Most likely to want to play a game",
		"1name" : "Malancha",
		"1points" : "6",
		"2name" : "Katie",
		"2points" : "5",
		"3name" : "Sarah",
		"3points" : "5",
		"4name" : "Mart",
		"4points" : "3",
		"5name" : "Shea",
		"5points" : "2",
		"6name" : "Sammy",
		"6points" : "1",
		"7name" : "Shannon",
		"7points" : "1",
		"8name" : "Tom",
		"8points" : "1",
	},
	{
		"superlatives" : "Best facial expressions",
		"1name" : "Mart",
		"1points" : "7",
		"2name" : "Grandma",
		"2points" : "3",
		"3name" : "Sammy",
		"3points" : "3",
		"4name" : "Tom",
		"4points" : "2",
		"5name" : "Nicole",
		"5points" : "2",
		"6name" : "Malancha",
		"6points" : "1",
		"7name" : "Peter or John",
		"7points" : "1",
		"8name" : "Kelsey / Alyssa",
		"8points" : "1",
	},
	{
		"superlatives" : "Most photogenic",
		"1name" : "Sarah",
		"1points" : "6",
		"2name" : "Johnny",
		"2points" : "4",
		"3name" : "Patti",
		"3points" : "3",
		"4name" : "Alyssa or Kelsey",
		"4points" : "2",
		"5name" : "Andrew or Shannon",
		"5points" : "2",
		"6name" : "Sammy",
		"6points" : "1",
		"7name" : "Grandpa or Grandma",
		"7points" : "1",
		"8name" : "Katie or Nicole",
		"8points" : "1",
	},
	{
		"superlatives" : "Most likely to be on a reality TV show",
		"1name" : "Sammy",
		"1points" : "10",
		"2name" : "Jessica",
		"2points" : "3",
		"3name" : "Peter",
		"3points" : "3",
		"4name" : "Josh",
		"4points" : "2",
		"5name" : "Nicole",
		"5points" : "2",
		"6name" : "LJ or Malancha",
		"6points" : "1",
		"7name" : "Tom, Kendra or Sarah",
		"7points" : "1",
		"8name" : "0",
		"8points" : "0",
	},
	{
		"superlatives" : "Most daring",
		"1name" : "Peter",
		"1points" : "4",
		"2name" : "Josh",
		"2points" : "4",
		"3name" : "Sammy",
		"3points" : "4",
		"4name" : "Jessica",
		"4points" : "3",
		"5name" : "LJ",
		"5points" : "2",
		"6name" : "Jim",
		"6points" : "2",
		"7name" : "Kelsey or Alyssa",
		"7points" : "2",
		"8name" : "Shannon or Andrew",
		"8points" : "2",
	},
	{
		"superlatives" : "Best nickname",
		"1name" : "Mart",
		"1points" : "10",
		"2name" : "Joe",
		"2points" : "3",
		"3name" : "John",
		"3points" : "3",
		"4name" : "Nicole",
		"4points" : "3",
		"5name" : "Andrew",
		"5points" : "3",
		"6name" : "Kaite",
		"6points" : "1",
		"7name" : "Grandpa or Katie",
		"7points" : "1",
		"8name" : "Jessica or Johnny",
		"8points" : "1",
	},
	{
		"superlatives" : "Sheep in wolves clothing",
		"1name" : "John",
		"1points" : "12",
		"2name" : "Tom",
		"2points" : "3",
		"3name" : "Josh",
		"3points" : "2",
		"4name" : "Peter",
		"4points" : "1",
		"5name" : "Shannon",
		"5points" : "1",
		"6name" : "Shea",
		"6points" : "1",
		"7name" : "Andrew",
		"7points" : "1",
		"8name" : "LJ",
		"8points" : "1",
	},
	{
		"superlatives" : "Most changed",
		"1name" : "Andrew",
		"1points" : "5",
		"2name" : "Shannon",
		"2points" : "3",
		"3name" : "John",
		"3points" : "3",
		"4name" : "Peter",
		"4points" : "3",
		"5name" : "Sarah or Sammy",
		"5points" : "2",
		"6name" : "Shea",
		"6points" : "2",
		"7name" : "Malancha or Mart",
		"7points" : "1",
		"8name" : "Nicole or Jessica",
		"8points" : "1",
	},
	{
		"superlatives" : "Biggest glow up",
		"1name" : "Kelsey",
		"1points" : "8",
		"2name" : "Grandma",
		"2points" : "3",
		"3name" : "Johnny",
		"3points" : "2",
		"4name" : "Sarah or Sammy",
		"4points" : "1",
		"5name" : "Jessica",
		"5points" : "1",
		"6name" : "LJ or Margaret",
		"6points" : "1",
		"7name" : "Mart or Katie",
		"7points" : "1",
		"8name" : "Mary or Joe",
		"8points" : "1",
	},
	{
		"superlatives" : "Biggest Night owl",
		"1name" : "Malancha",
		"1points" : "7",
		"2name" : "Sarah",
		"2points" : "7",
		"3name" : "LJ",
		"3points" : "4",
		"4name" : "Mary",
		"4points" : "3",
		"5name" : "Josh",
		"5points" : "2",
		"6name" : "Mart",
		"6points" : "1",
		"7name" : "Shannon",
		"7points" : "1",
		"8name" : "Greg",
		"8points" : "1",
	},
	{
		"superlatives" : "Biggest Early Bird",
		"1name" : "John",
		"1points" : "12",
		"2name" : "Chris",
		"2points" : "6",
		"3name" : "Jim",
		"3points" : "6",
		"4name" : "Greg",
		"4points" : "1",
		"5name" : "Grandpa",
		"5points" : "1",
		"6name" : "0",
		"6points" : "0",
		"7name" : "0",
		"7points" : "0",
		"8name" : "0",
		"8points" : "0",
	},
	{
		"superlatives" : "Sleeps in the latest",
		"1name" : "Malancha",
		"1points" : "13",
		"2name" : "Sarah",
		"2points" : "4",
		"3name" : "Josh",
		"3points" : "2",
		"4name" : "Greg",
		"4points" : "2",
		"5name" : "Mart",
		"5points" : "2",
		"6name" : "Mary",
		"6points" : "2",
		"7name" : "Joe",
		"7points" : "1",
		"8name" : "0",
		"8points" : "0",
	},
	{
		"superlatives" : "Most likely to curse",
		"1name" : "Patti",
		"1points" : "8",
		"2name" : "Jessica",
		"2points" : "8",
		"3name" : "John",
		"3points" : "4",
		"4name" : "Jim",
		"4points" : "3",
		"5name" : "Greg",
		"5points" : "2",
		"6name" : "Josh",
		"6points" : "1",
		"7name" : "0",
		"7points" : "0",
		"8name" : "0",
		"8points" : "0",
	},
	{
		"superlatives" : "Best Cook",
		"1name" : "Kendra",
		"1points" : "10",
		"2name" : "Greg",
		"2points" : "9",
		"3name" : "Grandma",
		"3points" : "2",
		"4name" : "Margaret",
		"4points" : "2",
		"5name" : "Patti",
		"5points" : "1",
		"6name" : "Grandpa",
		"6points" : "1",
		"7name" : "Mary",
		"7points" : "1",
		"8name" : "0",
		"8points" : "0",
	},
	{
		"superlatives" : "Most likely to be eating candy",
		"1name" : "Grandma",
		"1points" : "7",
		"2name" : "Shannon",
		"2points" : "6",
		"3name" : "Grandpa",
		"3points" : "5",
		"4name" : "Sammy",
		"4points" : "2",
		"5name" : "Katie",
		"5points" : "1",
		"6name" : "Shea",
		"6points" : "1",
		"7name" : "Mart or Katie",
		"7points" : "1",
		"8name" : "John or Patti",
		"8points" : "1",
	},
	{
		"superlatives" : "Most likely to make you smile",
		"1name" : "Grandpa",
		"1points" : "7",
		"2name" : "Katie",
		"2points" : "5",
		"3name" : "Shannon",
		"3points" : "4",
		"4name" : "Grandma",
		"4points" : "3",
		"5name" : "Greg",
		"5points" : "2",
		"6name" : "Alyssa",
		"6points" : "1",
		"7name" : "Shannon or Patti",
		"7points" : "1",
		"8name" : "Mart",
		"8points" : "1",
	},
	{
		"superlatives" : "Most likely to have a beer in their hand",
		"1name" : "Patti",
		"1points" : "11",
		"2name" : "Jessica",
		"2points" : "4",
		"3name" : "Josh",
		"3points" : "2",
		"4name" : "Nicole",
		"4points" : "2",
		"5name" : "Johnny",
		"5points" : "2",
		"6name" : "John",
		"6points" : "2",
		"7name" : "Shannon",
		"7points" : "1",
		"8name" : "Greg or Jim",
		"8points" : "1",
	},
	{
		"superlatives" : "Most likely to be on their phone",
		"1name" : "Sammy",
		"1points" : "11",
		"2name" : "Nicole",
		"2points" : "5",
		"3name" : "Tom",
		"3points" : "2",
		"4name" : "Mart",
		"4points" : "2",
		"5name" : "Jessica",
		"5points" : "1",
		"6name" : "Katie or Greg",
		"6points" : "1",
		"7name" : "Joe or Margaret",
		"7points" : "1",
		"8name" : "0",
		"8points" : "0",
	},
	{
		"superlatives" : "Most likely to be drawing",
		"1name" : "Shannon",
		"1points" : "20",
		"2name" : "Shea",
		"2points" : "2",
		"3name" : "Alyssa",
		"3points" : "1",
		"4name" : "LJ",
		"4points" : "1",
		"5name" : "Mart",
		"5points" : "1",
		"6name" : "0",
		"6points" : "0",
		"7name" : "0",
		"7points" : "0",
		"8name" : "0",
		"8points" : "0",
	},
	{
		"superlatives" : "Most likely to talk about work ",
		"1name" : "Tom",
		"1points" : "9",
		"2name" : "Margaret",
		"2points" : "8",
		"3name" : "Jim",
		"3points" : "4",
		"4name" : "Andrew",
		"4points" : "1",
		"5name" : "Grandma",
		"5points" : "1",
		"6name" : "John",
		"6points" : "1",
		"7name" : "Nicole",
		"7points" : "1",
		"8name" : "0",
		"8points" : "0",
	},
	{
		"superlatives" : "Best dancer",
		"1name" : "Jim",
		"1points" : "7",
		"2name" : "Shea",
		"2points" : "3",
		"3name" : "Andrew",
		"3points" : "2",
		"4name" : "Katie",
		"4points" : "2",
		"5name" : "Jessica",
		"5points" : "2",
		"6name" : "Greg",
		"6points" : "2",
		"7name" : "Kesley or Alyssa",
		"7points" : "1",
		"8name" : "Grandma",
		"8points" : "1",
	},
	{
		"superlatives" : "Best sense of humor",
		"1name" : "Mart",
		"1points" : "5",
		"2name" : "LJ",
		"2points" : "5",
		"3name" : "Katie",
		"3points" : "3",
		"4name" : "Johnny",
		"4points" : "2",
		"5name" : "Greg",
		"5points" : "2",
		"6name" : "Patti",
		"6points" : "2",
		"7name" : "Shea",
		"7points" : "1",
		"8name" : "Jessica",
		"8points" : "1",
	},


];